site:
  title: Spring Data DynamoDB
  start_page: spring-data-dynamodb::index.adoc
content:
  sources:
    - url: ../../..
      branches: HEAD
      start_path: src/main/antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ../../../build/site
